###

GET http://localhost:3398


###


POST http://localhost:3398/register

application/json

{
  "name": "test",
  "email": "test@abc.com",
  "password": "test"
}

###

POST http://localhost:3398/login

application/json

{
  "email": "test",
  "email": "test@abc.com",
  "password": "test"
}

